apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-node-app
  template:
    metadata:
      labels:
        app: example-node-app
    spec:
      containers:
      - name: example-node-app
        image: 370328998572.dkr.ecr.eu-west-1.amazonaws.com/example-node-app:492bc877ddb01c4d80765c433b23ff7fa312099f
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
