name: Application Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/example-node-app:${{ github.sha }} ./nodeapp
          docker push ${{ steps.login-ecr.outputs.registry }}/example-node-app:${{ github.sha }}
        env:
          AWS_DEFAULT_REGION: eu-west-1

      - name: Deploy Docker Image to EC2 and Update Kubernetes Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            sudo $(aws ecr get-login --no-include-email --region eu-west-1)
            kubectl set image deployment/example-node-app example-node-app=${{ steps.login-ecr.outputs.registry }}/example-node-app:${{ github.sha }}
